<?php

namespace Boilr\BoilrBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
    public function getValue($key, $default = null)
    {
        $record = $this->findOneByParameter($key);
        /* @var $record Config */

        if (! $record) {
            return $default;
        }

        return $record->getValue();
    }

    public function getArrayValue($key)
    {
        $value = $this->getValue($key);
        if ($value) {
            $array = explode(',', $value);

            return $array;
        }

        return null;
    }

    public function getDateTime($key)
    {
        $value = $this->getValue($key);
        $aDate = new \DateTime();

        $aDate->setTimestamp($value);

        return $aDate;
    }

    public function setValue($key, $parameter)
    {
        $success = true;
        $em      = $this->getEntityManager();

        $em->beginTransaction();
        try {
            $em->createQuery("UPDATE BoilrBundle:Config c SET c.value = :val WHERE c.setting = :key")
                ->setParameters(array('key' => $key, 'val' => $parameter))
                ->execute();

            $em->commit();
        } catch (\PDOException $exc) {
            $success = false;
            $em->rollback();
        }

        return $success;
    }

    public function setDateTime($key, \DateTime $aDate)
    {
        $value = $aDate->format('U');

        return $this->setValue($key, $value);
    }
}