<?php

namespace Boilr\BoilrBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstallerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallerRepository extends EntityRepository
{
}