_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

homepage:
    prefix:   /
    resource: "@BoilrBundle/Controller/DefaultController.php"
    type:     annotation

address:
    prefix:   /address
    resource: "@BoilrBundle/Controller/AddressController.php"
    type:     annotation

person:
    prefix:   /person
    resource: "@BoilrBundle/Controller/PersonController.php"
    type:     annotation

contract:
    prefix:   /contract
    resource: "@BoilrBundle/Controller/ContractController.php"
    type:     annotation

system:
    prefix:   /system
    resource: "@BoilrBundle/Controller/SystemController.php"
    type:     annotation

manteinance:
    prefix:   /manteinance
    resource: "@BoilrBundle/Controller/ManteinanceSchemaController.php"
    type:     annotation